Disable MariaDbSmokeTest if Docker is not available
The test was enabled as part of the transition to testcontainers v2,
but that transition fails in the plugin bill of materials because it is
running the tests inside a Docker container without allowing access to
the Docker socket or command line Docker.

Detected in plugin BOM pull request:

* https://github.com/jenkinsci/bom/pull/6369

Failure message was:

java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:274)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:265)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:154)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:196)
	at org.testcontainers.DockerClientFactory$1.getDockerClient(DockerClientFactory.java:108)
	at com.github.dockerjava.api.DockerClientDelegate.authConfig(DockerClientDelegate.java:109)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:316)
	at io.jenkins.plugins.flyway.MariaDbSmokeTest.smokeTest(MariaDbSmokeTest.java:23)

Amends 7ffa4333a7e65fa70286314e6c683117b6eaf858 from pull request:

* https://github.com/jenkinsci/flyway-api-plugin/pull/238

Will need a new release or the most recent release will need to be
reverted from the plugin BOM.